In [2]:
# import numpy
import numpy as np

In [28]:
# Step 2: Create NumPy Arrays
arr = np.array([2, 4, 6, 8, 10])
print(arr)

[ 2  4  6  8 10]


In [4]:
# checking type of array
print(type(arr))

<class 'numpy.ndarray'>


In [24]:
# Step 3: Create Arrays Quickly
zeros = np.zeros((2, 4))
ones = np.ones((3, 3))
range_array = np.arange(1, 10, 1).reshape(3,3)

print(zeros)
print(ones)
print(range_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# Step 4: Indexing & Slicing
# first element
# last element
# slicing

print(arr[0])
print(arr[-1])
print(arr[2:4])

2
10
[6 8]


In [32]:
# Step 5: Vectorized Operations (MOST IMPORTANT)

prices = np.array([100, 200, 300, 400])

# Apply 10% discount to all prices
discounted = prices * 0.9
print(discounted)

[ 90. 180. 270. 360.]


In [34]:
# Step 6: Mathematical Operations

print(np.sum(prices))
print(np.mean(prices))
print(np.max(prices))
print(np.min(prices))

1000
250.0
400
100


In [36]:
# Step 7: Conditional Operations

high_prices = prices[prices > 250]
print(high_prices)

[300 400]


In [38]:
# Step 8: Reshaping Arrays

matrix = np.arange(1, 7).reshape(2, 3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [40]:
# Step 9: NumPy with Pandas (Real Use Case)

import pandas as pd

df = pd.read_csv("Datasets/Cleaned_dataset_titanic.csv")

# Convert column to NumPy array
ages = df['age'].to_numpy()

print(np.mean(ages))
print(np.percentile(ages, 75))

29.69911764705882
35.0


In [42]:
# 🧪 Mini Challenges (Optional but Good)
# Apply a 15% increase to [500, 1000, 1500]
# Extract values greater than 30 from an array

prices = np.array([500, 1000, 1500])

increased = prices * 1.15
print(increased)

[ 575. 1150. 1725.]


In [44]:
data = np.array([10, 25, 30, 35, 40, 50])

greater_than_30 = data[data > 30]
print(greater_than_30)

[35 40 50]
